### ISSUE TITLE
FileNotFoundError: 'imagenet64_uncond_100M_1500K.pt'

### ISSUE THREAD

**Issue by JiaojiaoYe1994** [42Shawn/PTQ4DM#4]
Hi guys, I tried to run the provided demo, it has missed model checkpoint. It would be nice if someone could provide the model or potential solution.

To reproduce the error, run the following code:
```
cd PTQ4DM
bash quant_sample_ddim_in_backward_DNTC.sh
``` 

The returned result:
```
Logging to /tmp/openai-2023-05-24-20-30-55-642713
creating model and diffusion...
Traceback (most recent call last):
  File "improved-diffusion/scripts/quant_image_sample.py", line 532, in <module>
    main()
  File "improved-diffusion/scripts/quant_image_sample.py", line 319, in main
    model.load_state_dict(torch.load(args.model_path, map_location="cpu"))
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/shangyuzhang/diffusion_models/ptqdiffusionmodel/models/imagenet64_uncond_100M_1500K.pt'
```

**Comment by tqch** [comment]
I think it is the same as the OpenAI official checkpoint [[link]](https://openaipublic.blob.core.windows.net/diffusion/march-2021/imagenet64_uncond_100M_1500K.pt) in [[improved-diffusion]](https://github.com/openai/improved-diffusion).
